version: '3.2'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: container_realstate
    entrypoint: sh -c "celery -A tasks worker -l info -c 2"
    volumes:
      - '.:/var/www'
    ports:
      - "5501:5501"

networks:
  default:
    external:
      name: dev-network