version: '3.2'

services:
  python:
    build: .
    container_name: container_realstate
    # entrypoint: sh -c "celery -A src.shared.providers.queue worker -l info -c 2"
    volumes:
      - '.:/app'
    ports:
      - "5501:5501"


  redis:
    image: redis:6.2-bullseye
    container_name: container_redis_realstate
    ports: 
      - "6380:6379"

networks:
  default:
    external:
      name: dev-network